# Generated by Django 2.2.7 on 2019-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
